FROM openjdk:11
EXPOSE 8081
ADD ./target/CounselorService-1.0-SNAPSHOT-jar-with-dependencies.jar CounselorService-1.0-SNAPSHOT-jar-with-dependencies.jar
ENTRYPOINT ["java","-jar", "CounselorService-1.0-SNAPSHOT-jar-with-dependencies.jar"]