FROM openjdk:11
EXPOSE 8085
ADD ./target/RoomBookingService-1.0-SNAPSHOT-jar-with-dependencies.jar RoomBookingService-1.0-SNAPSHOT-jar-with-dependencies.jar
ENTRYPOINT ["java","-jar", "RoomBookingService-1.0-SNAPSHOT-jar-with-dependencies.jar"]